### PR TITLE
added loot_helion fix

### PR DESCRIPTION
**Pull request by Nolski**
Necessary for channel use. Also made file pep8 compliant.

### CODE REVIEW

**Comment by decause** [comment]
Sorry, no thanks.

**Comment by liam-middlebrook** [comment]
@decause why don't you fell like this should be a part of kettlefish?

**Comment by ryansb** [comment]
High priority fix for critical issue, should be merged urgently.

**Comment by oddshocks** [comment]
Remy, you can't give even give loot_helion a reason for wontfix? This isn't the GNOME 3 trac!

**Pull request closed without merging**
